### PR TITLE
Return a typed error

### PR DESCRIPTION
**Pull request by Jleagle**

### CODE REVIEW

**Comment by Jleagle** [comment]
@StefanSchroeder Also, is the main regex supposed to be commented out? Thanks.

**Comment by StefanSchroeder** [comment]
Hi @Jleagle thanks for the comment. The regex in IsRoman had a bug. I cannot remember what it was. I have updated the module today to clean it up a little without realizing that I had your PR open. I will merge it manually now. Thank you for your contribution. I appreciate it.

**Comment by StefanSchroeder** [comment]
Merged manually due to conflicts.

**Comment by Jleagle** [comment]
Thanks, could you version please as Roman() has a breaking change.

**Pull request closed without merging**
